### ISSUE TITLE
Failed to geocode address, no co-ordinates saved

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/org.wikimedia.geocoder#18]
I may be missing something obvious, but I've just installed the extension, ensuring beforehand that no geocoding or mapping provider was set. Post-install I noted that Geocoded was set in the UI as the geocoding provider. Taking the 'zero-config' at face value, I edited an address and got: "Failed to geocode address, no co-ordinates saved". 
Nothing in the Civi log. Civi 5.23.x with Wordpress.

**Comment by eileenmcnaughton** [comment]
@Upperholme it depends whether if can find the address at open street maps - you can see 

https://nominatim.openstreetmap.org/search/search?format=jsonv2&q=1+Downing+Street%2CLondon&addressdetails=1&limit=5

works but I just tried with my own address and it doesn't work if I include my rural delivery code - because that isn't understood

**Comment by edvanleeuwen** [comment]
I have the same problem.

When I enter the search described above with my own address, I get a proper result. But doing it from the UI, I get the error message.
