### ISSUE TITLE
Don't store Google geocoding results for more than 30 days

### ISSUE THREAD

**Issue by pnorman** [eileenmcnaughton/org.wikimedia.geocoder#2]
Google's new Terms of Service coming into effect on June 11th prohibit "stor[ing] Google Maps Content for more than 30 days". "Google Maps Content" is explicitly defined to include geocoding results.

**Comment by eileenmcnaughton** [comment]
@pnorman thank you - I certainly struggled to find clear information in the google policies. I have logged this issue against CiviCRM as it is primarily a feature of CiviCRM - https://lab.civicrm.org/dev/core/issues/167

**Comment by tttp** [comment]
@pnorman could you share the link to the ToS?

and a reminder why we need open data ;)

**Comment by pnorman** [comment]
The new terms are at https://cloud.google.com/maps-platform/terms

The relevant restrictions are 3.2.4 (a)

> (a)  No Scraping.  Customer will not extract, export, or scrape Google Maps Content for use outside the Services. For example, Customer will not:(i) pre-fetch, cache, index, or store Google Maps Content for more than 30 days; (ii) bulk download geocodes; or (iii) copy business names, addresses, or user reviews.

and 20

> "Google Maps Content" means any content provided through the Services (whether created by Google or its third-party licensors), including map and terrain data, imagery, traffic data, and places data (including business listings).

Geocoding-specific terms are at https://developers.google.com/maps/documentation/geocoding/policies and have the restriction

> The Geocoding API may only be used in conjunction with displaying results on a Google map. It is prohibited to use Geocoding API data without displaying a Google map.

**Comment by JoeMurray** [comment]
Grrr! So the supposedly non-evil empire is starting to charge for api calls and barring us from storing results! Create a dependency then monetize. Grrr. 

We do make use of lat/long results when displaying a map and it would be pretty simple to link the settings for the two in case of Google. We also separately use lat/long for proximity searches, which not all Civi orgs care about. An option that would probably be compliant would be to have a cron call to google every month to gecode each address, for orgs not using proximity searches. Maybe a notice that using Google causes proximity searches to be disabled, and if people accept that and proceed to choose them as geocoding and mapping provider then disable that search. 

Putting something into the default civi footer might be compliant re policy and terms notices.

My sense is that google is the preferred geocoding provider. @cividesk do you have data on this?

How to handle this on upgrade is a real issue due to need to turn things off to be compliant or to change mapping provider or to change geocoding provider. 

Not much time for this. Probably need a blog post too and a newsletter article.

**Comment by pnorman** [comment]
> Grrr! So the supposedly non-evil empire is starting to charge for api calls and barring us from storing results! Create a dependency then monetize. Grrr.

As far as I know, Google has *always* required that their geocoding results are only used for displaying on a map, and storing the results in a database was a no-no.

**Comment by davidalejandroaguilar** [comment]
The 30 days thing was removed from the TOS, now it says you definitely cannot cache it.

**Comment by pnorman** [comment]
Should I open a new issue about not storing Google geocoding results at all?

**Comment by nchaturv** [comment]
I just read the geocoding API terms here 
https://cloud.google.com/maps-platform/terms/maps-service-terms/

Bullet 3.4, and it does say :
3.4 Caching. Customer can temporarily cache latitude (lat) and longitude (lng) values from the Geocoding API for up to 30 consecutive calendar days, after which Customer must delete the cached latitude and longitude values. Customer can cache Geocoding API Place ID (place_id) values, in accordance with the Geocoding API Policies.

So you can cache it for 30 calendar days

**Comment by pnorman** [comment]
> So you can cache it for 30 calendar days

But not more, which is what the original issue is about.
